DROP TABLE POI_NODE_REF;
CREATE TABLE `POI_NODE_REF` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT , `LONGITUDE` DOUBLE PRECISION NOT NULL , `LATITUDE` DOUBLE PRECISION NOT NULL , `NODE_BACKEND_ID` VARCHAR NOT NULL , `ORDINAL` INTEGER NOT NULL , `POI_ID` BIGINT NOT NULL , `UPDATED` SMALLINT NOT NULL );
ALTER TABLE 'POI' RENAME to 'POI2';
CREATE TABLE `POI` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT , `LONGITUDE` DOUBLE PRECISION NOT NULL , `LATITUDE` DOUBLE PRECISION NOT NULL , `NAME` VARCHAR , `BACKEND_ID` VARCHAR , `VERSION` VARCHAR , `UPDATE_DATE` BIGINT , `VISIBLE` SMALLINT , `UPDATED` SMALLINT NOT NULL , `WAY` SMALLINT NOT NULL , `TO_DELETE` SMALLINT NOT NULL , `LEVEL` VARCHAR , `POI_TYPE_ID` BIGINT );
INSERT INTO POI(BACKEND_ID, ID, LATITUDE, LONGITUDE, NAME, POI_TYPE_ID, UPDATE_DATE, UPDATED, VERSION, VISIBLE, WAY, TO_DELETE, LEVEL) SELECT BACKEND_ID, ID, LATITUDE, LONGITUDE, NAME, POI_TYPE_ID, UPDATE_DATE, UPDATED, VERSION, VISIBLE, WAY, TO_DELETE, LEVEL FROM POI2
DROP TABLE POI2;
update POI_NODE_REF set UPDATED=0;